baseURL = "https://imzsh.com/"
languageCode = "en-us"
title = "求索日记"
theme = "nov"
paginate = 10

[outputs]
  home = ["HTML", "RSS", "JSON"]

[params]
  favicon = "https://img.shuxhan.com/favicon-2.png" # 
	subtitle = "路漫漫其修远兮，吾将上下而求索！"
  author = "Nov8nana"
	toc = true

[permalinks]
  posts = "/posts/:year:month:day"

[[menu.main]]
name = "首页"
url = "/"
weight = 1

[[menu.main]]
name = "归档"
url = "/posts"
weight = 2

[[menu.main]]
name = "标签"
url = "/tags"
weight = 3

[[menu.main]]
name = "关于我"
url = "/about"
weight = 4

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""     
    lineNoStart = 1  
    lineNos = false
    lineNumbersInTable = false
    noClasses = true
    style = "dracula"
    tabWidth = 4
    anchorlinenos = false
  [markup.tableOfContents]
    endLevel = 3
    ordered = false
    startLevel = 2

