baseURL = "https://shuxhan.com/"
languageCode = "en-us"
title = "求索日记"
theme = "nov"
paginate = 7

[params]
  favicon = "https://img.shuxhan.com/favicon.png"
  authorname = "Nov8nana"
  authorimg = "https://img.shuxhan.com/author.png"
	subtitle = "路漫漫其修远兮，吾将上下而求索！"

	# Enable a table of contents
	toc = true

[permalinks]
  posts = "/posts/:year:month:day"

[[menu.main]]
name = "首页"
url = "/"
weight = 1

[[menu.main]]
name = "归档"
url = "/posts"
weight = 2

[[menu.main]]
name = "编程技术"
url = "/categories/编程技术/"
weight = 3

[[menu.main]]
name = "生活随笔"
url = "/categories/生活随笔"
weight = 4

[[menu.main]]
name = "关于我"
url = "/about"
weight = 5

[[params.social]]
name = "Github"
icon = "github"
url = "https://github.com/Nov8nana/"

[[params.social]]
name = "RSS"
icon = "rss"
url = "/index.xml"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""     
    lineNoStart = 1  
    lineNos = false
    lineNumbersInTable = false
    noClasses = true
    style = "dracula"
    tabWidth = 4
    anchorlinenos = false
  [markup.tableOfContents]
    endLevel = 3
    ordered = false
    startLevel = 2
